# Development profile overrides
spring.profiles.active=dev

# Enable debug logging
logging.level.root=DEBUG
logging.file.name=logs/application-dev.log

# Development datasource (local SQL Server Express)
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=WebApiExampleDev;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=

# Hibernate DDL auto
spring.jpa.hibernate.ddl-auto=create-drop
